/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAiAnalysisRouteImport } from './routes/_app.ai-analysis'
import { Route as AppContradictionsRouteImport } from './routes/_app.contradictions'
import { Route as AppCorrelationRouteImport } from './routes/_app.correlation'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppExternalRecordsRouteImport } from './routes/_app.external-records'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app.cases.$caseId'
import { Route as AppEvidenceIndexRouteImport } from './routes/_app.evidence.index'
import { Route as AppEvidenceEvidenceIdRouteImport } from './routes/_app.evidence.$evidenceId'
import { Route as AppEvidenceUploadRouteImport } from './routes/_app.evidence.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiAnalysisRoute = AppAiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppContradictionsRoute = AppContradictionsRouteImport.update({
  id: '/contradictions',
  path: '/contradictions',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrelationRoute = AppCorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExternalRecordsRoute = AppExternalRecordsRouteImport.update({
  id: '/external-records',
  path: '/external-records',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceIndexRoute = AppEvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceEvidenceIdRoute = AppEvidenceEvidenceIdRouteImport.update({
  id: '/evidence/$evidenceId',
  path: '/evidence/$evidenceId',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceUploadRoute = AppEvidenceUploadRouteImport.update({
  id: '/evidence/upload',
  path: '/evidence/upload',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/contradictions': typeof AppContradictionsRoute
  '/correlation': typeof AppCorrelationRoute
  '/dashboard': typeof AppDashboardRoute
  '/external-records': typeof AppExternalRecordsRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/evidence/upload': typeof AppEvidenceUploadRoute
  '/cases/': typeof AppCasesIndexRoute
  '/evidence/': typeof AppEvidenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AppAiAnalysisRoute
  '/contradictions': typeof AppContradictionsRoute
  '/correlation': typeof AppCorrelationRoute
  '/dashboard': typeof AppDashboardRoute
  '/external-records': typeof AppExternalRecordsRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/evidence/upload': typeof AppEvidenceUploadRoute
  '/cases': typeof AppCasesIndexRoute
  '/evidence': typeof AppEvidenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-analysis': typeof AppAiAnalysisRoute
  '/_app/contradictions': typeof AppContradictionsRoute
  '/_app/correlation': typeof AppCorrelationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/external-records': typeof AppExternalRecordsRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/evidence/$evidenceId': typeof AppEvidenceEvidenceIdRoute
  '/_app/evidence/upload': typeof AppEvidenceUploadRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/evidence/': typeof AppEvidenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/contradictions'
    | '/correlation'
    | '/dashboard'
    | '/external-records'
    | '/cases/$caseId'
    | '/evidence/$evidenceId'
    | '/evidence/upload'
    | '/cases/'
    | '/evidence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/contradictions'
    | '/correlation'
    | '/dashboard'
    | '/external-records'
    | '/cases/$caseId'
    | '/evidence/$evidenceId'
    | '/evidence/upload'
    | '/cases'
    | '/evidence'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-analysis'
    | '/_app/contradictions'
    | '/_app/correlation'
    | '/_app/dashboard'
    | '/_app/external-records'
    | '/_app/cases/$caseId'
    | '/_app/evidence/$evidenceId'
    | '/_app/evidence/upload'
    | '/_app/cases/'
    | '/_app/evidence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-analysis': {
      id: '/_app/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AppAiAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contradictions': {
      id: '/_app/contradictions'
      path: '/contradictions'
      fullPath: '/contradictions'
      preLoaderRoute: typeof AppContradictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correlation': {
      id: '/_app/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof AppCorrelationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/external-records': {
      id: '/_app/external-records'
      path: '/external-records'
      fullPath: '/external-records'
      preLoaderRoute: typeof AppExternalRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/': {
      id: '/_app/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof AppEvidenceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/$evidenceId': {
      id: '/_app/evidence/$evidenceId'
      path: '/evidence/$evidenceId'
      fullPath: '/evidence/$evidenceId'
      preLoaderRoute: typeof AppEvidenceEvidenceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/upload': {
      id: '/_app/evidence/upload'
      path: '/evidence/upload'
      fullPath: '/evidence/upload'
      preLoaderRoute: typeof AppEvidenceUploadRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAnalysisRoute: typeof AppAiAnalysisRoute
  AppContradictionsRoute: typeof AppContradictionsRoute
  AppCorrelationRoute: typeof AppCorrelationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExternalRecordsRoute: typeof AppExternalRecordsRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppEvidenceEvidenceIdRoute: typeof AppEvidenceEvidenceIdRoute
  AppEvidenceUploadRoute: typeof AppEvidenceUploadRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppEvidenceIndexRoute: typeof AppEvidenceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAnalysisRoute: AppAiAnalysisRoute,
  AppContradictionsRoute: AppContradictionsRoute,
  AppCorrelationRoute: AppCorrelationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExternalRecordsRoute: AppExternalRecordsRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppEvidenceEvidenceIdRoute: AppEvidenceEvidenceIdRoute,
  AppEvidenceUploadRoute: AppEvidenceUploadRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppEvidenceIndexRoute: AppEvidenceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
